language: java
before_install:
  - "git clone https://github.com/Mind4SE/mind-compiler.git"
  - "cd mind-compiler"
  - "mvn -U install -DskipTests -PCI-profile"
  - "cd .."
install:
  - "cd fractal-runtime-cpp"
  - "mvn -U clean"
  - "cd .."
  - "cd adl-backend-cpp"
  - "mvn -U clean"
  - "cd .."
  - "cd idl-backend-cpp"
  - "mvn -U clean"
  - "cd .."
  - "cd mindcpp"
  - "mvn -U clean"
  - "cd .."
script:
  - "cd fractal-runtime-cpp"
  - "mvn -U install"
  - "cd .."
  - "cd adl-backend-cpp"
  - "mvn -U install"
  - "cd .."
  - "cd idl-backend-cpp"
  - "mvn -U install"
  - "cd .."
  - "cd mindcpp"
  - "mvn -U verify"
